### ISSUE TITLE
Interested in clj-http -> clj-http-lite?

### ISSUE THREAD

**Issue by lvh** [gws/clj-mandrill#2]
I've forked this library to a) update some deps (happy to upstream that in a PR) but I'm going to b) replace clj-http with [clj-http-lite](https://github.com/martinklepsch/clj-http-lite). It only supports a subset of clj-http's features (mostly parts you don't really use, except you have to manually decode the JSON body, instead of `:as :json`) and uses java's builtin URL openers instead of the Apache HTTP client.

This has two benefits:

1. For everyone: smaller jars.
2. For people building native-image binaries with GraalVM: it works (the Apache HTTP client does not)

I particularly care about the latter but the former is a neat side effect.

I'm trying to figure out if you would prefer a friendly fork, or an upstreamed PR. I'm happy either way (and am going to do the work either way) -- the only question is where the work ends up.

Thanks for clj-mandrill either way :)

**Comment by gws** [comment]
@lvh Hey! I hadn't been doing a good job of maintaining this library since I stopped using Mandrill (and probably should put a notice to that effect) but glad it is useful to you.

I'm happy to accept the PR if you get a chance, but don't mind a friendly fork if you want to go that route instead. This gives me some motivation to bump dependencies and get back in the habit of maintaining some of my code.

Thank you!

**Comment by lvh** [comment]
Sounds good! It's not entirely clear I'll end up using this either, but if I do I'll write the clj-http-lite version and see what transfers over cleanly.

(I'll close this for now since the real thing I needed was to know if you wanted patches or not and your response answered that perfectly :-))
